### ISSUE TITLE
TypeScript 4.8 fails with `openapi-types`

### ISSUE THREAD

**Issue by tvardy** [kogosoftwarellc/open-api#833]
When updated from TS 4.7.4 to 4.8.2 I'm getting this error during the build:

```
node_modules/openapi-types/dist/index.d.ts:16:28 - error TS2344: Type 'T' does not satisfy the constraint '{}'.

16         paths: PathsObject<T>;
                              ~

  node_modules/openapi-types/dist/index.d.ts:15:34
    15     type PathsWebhooksComponents<T> = {
                                        ~
    This type parameter might need an `extends {}` constraint.


Found 1 error in node_modules/openapi-types/dist/index.d.ts:16
```

I checked the TypeScripts changelog and this was actually introduced with the `4.8.0-beta` version.
Check here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-beta/#unconstrained-generics-no-longer-assignable-to

**Comment by jsdevel** [comment]
@tvardy please submit a PR to fix this

**Comment by brianphillips** [comment]
I'm pretty sure this is fixed by #830
